obj-y += app_channel.o
obj-$(CONFIG_APP_ENABLE) += app_handler.o
ifndef CONFIG_PLATFORM_SITL
obj-y += bootloader.o
endif
obj-y += collision_avoidance.o
obj-y += collision_avoidance.o
obj-y += commander.o
obj-y += comm.o
obj-y += console.o
obj-y += crtp_commander_generic.o
obj-y += crtp_commander_high_level.o
obj-y += crtp_commander.o
obj-y += crtp_commander_rpyt.o
obj-y += crtp_localization_service.o
obj-y += crtp.o
obj-y += crtpservice.o
ifndef CONFIG_PLATFORM_SITL
obj-y += esp_deck_flasher.o
endif
ifndef CONFIG_PLATFORM_SITL
obj-y += eventtrigger.o
endif
ifndef CONFIG_PLATFORM_SITL
obj-y += extrx.o
obj-y += health.o
endif
obj-$(CONFIG_ESTIMATOR_KALMAN_ENABLE) += kalman_supervisor.o
obj-y += axis3fSubSampler.o
obj-y += log.o
obj-y += mem.o
obj-y += crtp_mem.o
obj-y += msp.o
obj-y += param_logic.o
obj-y += param_task.o
obj-y += peer_localization.o
obj-y += planner.o
obj-y += platformservice.o
obj-$(CONFIG_POWER_DISTRIBUTION_QUADROTOR) += power_distribution_quadrotor.o
obj-$(CONFIG_POWER_DISTRIBUTION_FLAPPER) += power_distribution_flapper.o
obj-$(CONFIG_PLATFORM_SITL) += power_distribution_sitl.o
obj-y += pptraj_compressed.o
obj-y += pptraj.o
obj-y += queuemonitor.o
obj-y += range.o
obj-y += sensfusion6.o
ifndef CONFIG_PLATFORM_SITL
obj-y += serial_4way_avrootloader.o
obj-y += serial_4way.o
obj-y += sound_cf2.o
endif
obj-y += stabilizer.o
obj-y += static_mem.o
obj-y += supervisor.o
obj-y += supervisor_state_machine.o
obj-y += sysload.o
obj-y += system.o
obj-$(CONFIG_DECK_LOCO) += tdoaEngineInstance.o
ifndef CONFIG_PLATFORM_SITL
obj-y += vcp_esc_passthrough.o
endif
obj-y += worker.o

# Sub folders
obj-$(CONFIG_ESTIMATOR_KALMAN_ENABLE) += kalman_core/
ifndef CONFIG_PLATFORM_SITL
obj-y += lighthouse/
endif
obj-y += controller/
obj-y += estimator/
ifndef CONFIG_PLATFORM_SITL
obj-y += cpx/
obj-y += p2pDTR/
endif
obj-y += outlierfilter/
