# Include for all platforms
obj-y += hal/
obj-y += init/
obj-y += modules/
obj-y += platform/
obj-y += utils/

# Exclude for SITL
ifndef CONFIG_PLATFORM_SITL
obj-y += deck/
obj-y += drivers/
obj-y += lib/
endif

